model:
  base_learning_rate: 1.0e-06   # 1.0e-5 set to target_lr by starting main.py with '--scale_lr False'
  target: lsdm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195  # 0.0155
    num_timesteps_cond: 1  # how many time steps to ignore the conditions
    log_every_t: 200  # used in progressive row
    timesteps: 1000
    # loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "label"  # useless in LSDM?
    conditioning_key: "SPADE"
    image_size: 128
    channels: 3
    cond_stage_trainable: False
    concat_mode: True
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    # scheduler_config: # 10000 warmup steps
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [10000]
    #     cycle_lengths: [10000000000000]
    #     f_start: [1.e-6]
    #     f_max: [1.]
    #     f_min: [ 1.]

    unet_config:
      target: lsdm.modules.diffusionmodules.openaimodel.UNetSPADEModel
      params:
        image_size: 128
        in_channels: 3  # 3 additional channels for segmentation maps (same first stage encoder)
        out_channels: 3
        model_channels: 192  # 192
        attention_resolutions: [ 16, 8, 4, 2 ]   # 32, 16, 8, 4
        num_semantic_labels: 8  # important!
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        ckpt_path: "logs/lsdm_kl_128x128x3_512resolution/epoch122.ckpt"  # lsdm checkpoint
        
    first_stage_config:
      target: lsdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "logs/autoencoder_kl_128x128x3_512resolution/epoch19.ckpt"  # autoencoder checkpoint
        # totally copy the autoencoder config:
        ddconfig:
          double_z: True  # True
          z_channels: 3
          resolution: 512  # 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"  # share the same encoder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 2
    wrap: False
    train:
      target: lsdm.data.lidc.LIDCDatasetCropOneHotTrain
      params:
        size: 512
        downscale_f: 8
    validation:
      target: lsdm.data.lidc.LIDCDatasetCropOneHotValidation
      params:
        size: 512
        downscale_f: 8

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False
        # change the settings in pl_module.log_images:
        log_images_kwargs:
          sample: True
          plot_diffusion_rows: False
          inpaint: False
          plot_progressive_rows: False

  trainer:
    benchmark: True
