model:
  base_learning_rate: 1.0e-06   # 1.0e-5 set to target_lr by starting main.py with '--scale_lr False'
  target: lsdm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195  # 0.0155
    num_timesteps_cond: 1  # how many time steps to ignore the conditions
    log_every_t: 200  # used in progressive row
    timesteps: 1000
    # loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "label"  # useless in LSDM?
    conditioning_key: "SPADE+concat"
    image_size: 60
    channels: 3
    cond_stage_trainable: False
    concat_mode: True
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    # scheduler_config: # 10000 warmup steps
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [10000]
    #     cycle_lengths: [10000000000000]
    #     f_start: [1.e-6]
    #     f_max: [1.]
    #     f_min: [ 1.]

    unet_config:
      target: lsdm.modules.diffusionmodules.openaimodel.UNetSPADEModel
      params:
        image_size: 60
        in_channels: 6  # 3 additional channels for segmentation maps (same first stage encoder)
        out_channels: 3
        model_channels: 128  # 192
        attention_resolutions: [ 8, 4, 2 ]   # 32, 16, 8, 4
        num_semantic_labels: 5  # important!
        num_res_blocks: 2
        # size has changed:
        channel_mult: [ 1,2,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        ckpt_path: "/home/zuxinrui/thesis-LSDM/nodule_malignancy/LSDM/logs/BrainMRI3/lsdm/last.ckpt"  # lsdm checkpoint (used in generation process)

    first_stage_config:
      target: lsdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "/home/zuxinrui/thesis-LSDM/nodule_malignancy/LSDM/logs/BrainMRI3/ae/last.ckpt"  # autoencoder checkpoint
        # totally copy the autoencoder config:
        ddconfig:
          double_z: True  # True
          z_channels: 3
          resolution: 240  # 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_first_stage__"  # share the same encoder __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8  # 8 for A100 [ 16, 8, 4 ] 1,2,2,4,4
    num_workers: 0
    wrap: True
    train:
      target: lsdm.data.general.DatasetAPITrain
      params:
        dataset_dir: "/deepstore/datasets/ram/nodule-ct-gen/LSDM/BrainMRI3"
        size: 240
        num_semantic_labels: 5  # [0,1,2,3,4]
    validation:
      target: lsdm.data.general.DatasetAPIValidation
      params:
        dataset_dir: "/deepstore/datasets/ram/nodule-ct-gen/LSDM/BrainMRI3"
        size: 240
        num_semantic_labels: 5  # BreastMam: 3  LIDC: 8

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False
        # change the settings in pl_module.log_images:
        log_images_kwargs:
          sample: True
          plot_diffusion_rows: False
          inpaint: False
          plot_progressive_rows: False

  trainer:
    benchmark: True
